### ISSUE TITLE
Tracking issue for #156 and #182

### ISSUE THREAD

**Issue by rfuest** [jamwaffles/embedded-graphics#314]
This is a tracking issue for the ongoing work on issues #156 and #182.
- [x] Change `Rectangle` to use top-left and size (#290)
- [x] Add `Points` iterators (#307)
- [x] Use `Rectangle` for `Dimensions` trait (#312)
- [x] Fix circle `Dimensions` (#317)
- [x] Add `contains(point: Point)` method to primitives (#318)
- [x] Support stroke alignment in `PrimitiveStyle` (#331)
- [x] Add `bottom_right()` getter to `Rectangle` (#333)
- [x] Use `bottom_right` in `Rectangle::contains` (#333)
- [x] `line::Points` should return exactly one `Point` for `start == end` (#353)
- [x] Check duplicate points (https://github.com/jamwaffles/embedded-graphics/pull/292#discussion_r419618612, [this test](https://github.com/jamwaffles/embedded-graphics/pull/292/files#diff-c1953210af5a72934cade95ee9ef2334R447-R455))
- [x] Add `fill_area` and `stroke_area` methods for styled primitives (#400)
- Reduce code duplication for styled and points iterators
  - [x] Circle (#317)
  - [x] Rectangle (#319)
  - [x] Line (#353)
  - [x] Triangle (#363)
- ~[ ] `Dimension` for styled primitive should consider stroke width and alignment~ (migrated to issue #428)
- ~[ ] Add more tests to check that drawing is consistent with #182~
- ~[ ] Rename `ContainsPoint`? (see https://github.com/jamwaffles/embedded-graphics/pull/318#issuecomment-611607535)~
- ~[ ] Investigate why performance of `cargo bench 'unfilled rectangle'` was reduced by 50% in PR #319~ (Rectangles are now drawn without using the iterator, so this should be invalid now)
- ~[ ] Support thick strokes and stroke alignment for triangles (or add note if it doesn't work https://github.com/jamwaffles/embedded-graphics/pull/331#pullrequestreview-400205527) ~ (will be implemented as part of PR #386)

**Comment by rfuest** [comment]
I will close this issue and open individual issues for the remaining points to make it easier to track using the project.

**Comment by jamwaffles** [comment]
Sounds good, thanks
