### ISSUE TITLE
Release 0.7.0-alpha.1

### ISSUE THREAD

**Issue by jamwaffles** [jamwaffles/embedded-graphics#380]
Issues/features left before cutting 0.7.0-alpha.1:

* [ ] #281 - Add SubImage
* [ ] #282 - 0.7.0 migration guide
* [ ] #314 - Tracking issue for #156 and #182
* [ ] #330 - DrawTarget improvements
* [x] #338 - Discuss extending the public Points and Size API
* [ ] #365 - Initial SparseIterator experiment
* [ ] #367 - ImageDimensions trait could use Size
* [ ] #382 - Add release checklist

(@rfuest please edit the above list with ones you'd like to see. There are others I haven't added as well but I cba to go through the issues list right now)

**Comment by rfuest** [comment]
Sorry, I forgot about this issue. I've added some issues I would like to include in 0.7.0-alpha.1.

**Comment by jamwaffles** [comment]
I've added all the above issues/PRs to the `0.7.0-alpha.1` project. I'd like to get back to using projects to track releases as they're a bit more automated, so I'm going to close this issue to avoid duplication. For anything else that should go in 0.7.0-alpha.1, please assign the issue/PR to the project.
